surprising_facts = {
    0: "Artemis 2, which launched in April 2026, is the first crewed mission outside the low-earth orbit. it is a lunar flyby, and will pave the way for future moon landings yay.",
    1: "The ancient Romans used concrete that could set underwater, a technology modern engineers only recently began to fully replicate.",
    2: "In the 1800s, doctors sometimes prescribed morphine for almost anything, including depression and headaches.",
    3: "During the Cold War, the U.S. trained dolphins to detect underwater mines and enemy submarines.",
    4: "In 17th-century Europe, coffee was sometimes banned because it was believed to cause radical thinking.",
    5: "In 1952, a massive smog in London was so thick it stopped public transportation for days and caused thousands of deaths.",
    6: "The first chemical element discovered by humans was phosphorus, isolated from urine in 1669.",
    7: "The oldest known written recipe is for beer and comes from ancient Sumeria over 4,000 years ago.",
    8: "Before the invention of the microscope, people believed that diseases were caused by 'bad air' and invisible spirits.",
    9: "In medieval Europe, 'trial by ordeal' involved dangerous tests like holding hot iron to prove innocence.",
    10: "Jupiter’s Great Red Spot is a storm larger than Earth that has been raging for at least 400 years.",
    11: "In the early 20th century, radium-infused water was marketed as a health tonic.",
    12: "During the Renaissance, some artists used tiny glass beads called 'murrine' to paint intricate patterns in jewelry and mosaics.",
    13: "The first known surgical operation to remove a tumor was performed in ancient India over 2,000 years ago.",
    14: "In 19th-century Paris, gas lighting was introduced to streets before indoor lighting became common.",
    15: "The earliest known map of the stars was created on a clay tablet in Babylon around 1200 BC.",
    16: "The first artificial sweetener, saccharin, was accidentally discovered in 1879 by a chemist working with coal tar derivatives.",
    17: "Vikings reached North America around 1,000 AD, centuries before Columbus.",
    18: "Ancient Chinese inventors created kites not just for recreation, but for measuring distances and signaling armies.",
    19: "During the 1800s, ether and chloroform were used to perform painless surgeries before modern anesthesia.",
    20: "Water can boil and freeze at the same time under a process called the 'triple point.'",
    21: "The Library of Congress in the U.S. was partially destroyed by fire in 1814 during the War of 1812.",
    22: "In the 1930s, some cities conducted aerial surveys with pigeons carrying cameras tied to them.",
    23: "The first known prosthetic limb, made of wood, dates back over 3,000 years to ancient Egypt.",
    24: "D-Day was the largest naval and amphibious operation in the history of man-kind. It re-introduced the Western front in WW2",
    25: "Marie Curie carried test tubes of radioactive materials in her pocket, unaware of the dangers.",
    26: "The phenomenon of ‘cosmic rays’ was discovered when particles from space were detected on Earth in the early 20th century.",
    27: "In 16th-century Europe, tulip bulbs became so valuable that they sparked economic bubbles known as ‘tulip mania.’",
    28: "Saturn’s rings are mostly made of ice and can be up to 30 feet thick in places.",
    29: "The first recorded vaccination was performed by Edward Jenner in 1796 to protect against smallpox.",
    30: "During WWII, Britain used inflatable tanks and fake aircraft to trick German reconnaissance.",
    31: "The earliest mechanical clocks were invented in China during the Tang dynasty in the 8th century.",
    32: "The concept of zero as a number was first developed in India around the 5th century AD.",
    33: "Ancient Egyptians were among the first to perform surgeries like cataract removal using specialized tools.",
    34: "The phenomenon of continental drift wasn’t widely accepted until the 1960s, despite being proposed in 1912 by Alfred Wegener.",
    35: "Some species of bacteria can survive extreme radiation that would instantly kill humans.",
    36: "The first public demonstration of a steam engine was in 1712 by Thomas Newcomen.",
    37: "In the early 1900s, peanut butter was considered a health food for invalids and children.",
    38: "The first known library, dating back to 2600 BC, was discovered in the ancient city of Ebla in Syria.",
    39: "A war was fought between 2 Italian city-states over a wooden bucket.",
    40: "Venus’ surface temperature is hot enough to melt lead due to a runaway greenhouse effect.",
    41: "The concept of vaccination existed in ancient China and India, where smallpox scabs were used for inoculation centuries before Jenner.",
    42: "In 18th-century England, pineapples were so rare that they were rented out for display at parties.",
    43: "The first powered flight in history, by the Wright brothers in 1903, lasted only 12 seconds.",
    44: "The Antikythera mechanism, built around 100 BC, is considered the world’s first analog computer.",
    45: "The oldest known star chart was discovered in the tomb of Senenmut, an ancient Egyptian architect.",
    46: "During the Renaissance, people believed bathing too often was dangerous and could cause illness.",
    47: "The first photograph ever taken of a human being was in 1838 by Louis Daguerre, captured by accident as a person stood too still.",
    48: "During the 19th century, some European cities held public executions as a form of entertainment.",
    49: "The first known prosthetic eye was found in Iran and dates back over 5,000 years.",
    50: "The earliest recorded description of the Milky Way comes from the Babylonian astronomers around 1000 BC.",
}
